<?php
/**
 * Media Gallery & Product Videos extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Mediaappearance
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 **/
?>


<?php
	$popupWidth  = Mage::getStoreConfig('mediaappearance/popupsettings/width');
	$popupHeight = Mage::getStoreConfig('mediaappearance/popupsettings/height');
	$autoPlay 	 = Mage::getStoreConfig('mediaappearance/popupsettings/autoplay');
	$playAgain 	 = Mage::getStoreConfig('mediaappearance/popupsettings/playagain');

?>


<div class="media_gallery_grid clearfix">
 <h3><span><?php echo $this->__('Media Gallery')?></span></h3>
  <div class="grid clearfix">
  <ul class="media_grid">
	<?php $collection = $this->getItems(); ?>
    	<?php if ( count($collection) == 0 ) : ?>
        <p class="text_1"><?php echo $this->__('No Media yet...'); ?></p>
        <?php else : ?>
            <div class="row_main" <?php if($_columnCount == 3) {?>style="padding-left:0px;" <?php } else {?> style="padding-left:30px;" <?php } ?> >
            <?php $_collectionSize = count($collection); ?>
            <?php $i=1; foreach ( $collection as $_item ) : ?> 	
            	<?php
					if($_item["mediatype"] == "1") {
						
						$videoURL = Mage::getBaseUrl('media').$_item["filename"];
						$videoRel = 'shadowbox; height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.autoPlay.'}}';
						 if($_item["filethumb"] != "") {
							$imgURL = Mage::helper('mediaappearance')->resizeImage($_item["filethumb"]);
						} else {
							$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon.jpg";
						} 
						
					} elseif ($_item["mediatype"] == "2") {
						
						//For Thumb
						$videoURL = $_item["videourl"];
						$videoData = Mage::helper('mediaappearance')->video_info($_item["videourl"]);
						if ($videoData!==false) {
							if($_item["filethumb"] != "") {
									$imgURL = Mage::helper('mediaappearance')->resizeImage($_item["filethumb"]);
								} else {
									$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
								}
							
						} else {
							if($_item["filethumb"] != "") {
								$imgURL = Mage::getBaseUrl('media').$_item["filethumb"];
							} else {
								$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
							}
						}
						
						//For Video URL
						if ($videoData!==false) {
							
							$video_type  = $videoData['video_type'];
							$video_id    = $videoData['video_id'];
							if($video_type == "vimeo") {
								$videoRel = "shadowbox;height=".$popupHeight.";width=".$popupWidth.";options={flashVars:{autostart: ".$autoPlay."}}";
								$videoURL = 'http://vimeo.com/moogaloop.swf?clip_id='.$video_id.'&autoplay=1';
							} elseif($video_type == "youtube") {
								$videoRel = 'shadowbox;height='.$popupHeight.';width='.$popupWidth.'; options={flashVars:{autostart: '.$autoPlay.'}}';
								$videoURL = "http://www.youtube.com/v/".$video_id;
							} 
							
						} else {
							
							$videoURL = $_item["videourl"];
							$videoRel = 'shadowbox;height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.$autoPlay.'}}';
							
						}
					} else {
						$videoRel = "";
						$videoURL = "#";
						$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
					}	
				?>
        		<li>
                <a class="sbox" href="<?php echo $videoURL; ?>" title="<?php echo $_item['title']; ?>" rel="<?php echo $videoRel; ?>">
                	
                	 <img src="<?php echo $imgURL; ?>"  alt="<?php echo $_media["title"]; ?>" border="0" /></a><br />
                    <h4>
                    	<a href="<?php echo $videoURL; ?>" title="<?php echo $_item['title']; ?>" rel="<?php echo $videoRel; ?>" class="sbox">
                    	<?php echo $_item['title']; ?>
                    	</a>
                    	<a class="sbox" href="<?php echo $videoURL; ?>" title="<?php echo $_item['title']; ?>" rel="<?php echo $videoRel; ?>" >

                    	<img src="<?php echo Mage::getBaseUrl('media').'mediaappearance/video_icon.png'?>">
                    	</a>
                    </h4>
                    </a>
                </li>
                <?php endforeach; ?>
                </ul>
        <?php endif;?>
		</div>
        <br  style="clear:both;" />
                <?php if ( $collection instanceof Zend_Paginator ) : ?>
                <?php echo $this->getChildHtml('pagination'); ?>
                <?php endif; ?>
                <?php echo $this->getChildHtml('toolbar'); ?>
                

        
                  
                
</div>
<div style="height:10px;"></div>   
<?php $loader = Mage::getBaseUrl('media').'mediaappearance/' . Mage::getStoreConfig('mediaappearance/ajaxloader/fme_media_img');?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>mediaappearance/jquery.ias.min.js"></script>



<script type="text/javascript">


jQuery.ias({
    container : '.grid',
    item: '.media_grid',
    pagination: '.media_gallery_grid .paginationControl',
    next: '.next a',
    loader: '<img src="<?php echo $loader;  ?>" id="popup" /><h4 id="popupsp"></h4>'
});
</script>

