<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="block block-specials">
        <div class="block-title">
            <strong><span><?php echo $this->__('Specials') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ul class="products-grid" id="widget-catalogsale-products-<?php echo $suffix; ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item col-xs-12">
                    <div class="grid_wrap">
                    <span class="sale_label"><?php echo $this->__('Sale') ?></span>
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-shop">
																									<?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
                         <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                         <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <div><a href="<?php echo $_product->getProductUrl() ?>" class="link_details"><?php echo $this->__('Details') ?></a></div> 
                        </div>
                    </div>
                      <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                        <div class="label-product">             
                            <?php if($_product->getData('new')){echo '<span class="new">'.$this->__('New').'</span>';  }?>
                            <?php if($_product->getData('sale')){echo '<span class="sale">'.$this->__('Sale').'</span>';  }?>
                        </div>
                   </div>
                </li>
            <?php endforeach; ?>
            </ul>
            </div>
            <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
</div>
<?php endif; ?>
