<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Mageplace_Hideprice
 */
?>
<?php
/** @var $this Mageplace_Hideprice_Block_Adminhtml_Catalog_Product_Edit */
?>
<?php echo $this->getFormInitScripts() ?>
    <div class="content-header">
        <?php echo $this->getHeaderHtml() ?>
        <p class="content-buttons form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
    </div>


    <form action="<?php echo $this->getSaveUrl() ?>" method="post" id="edit_form">
        <?php if (!$this->isSingleStoreMode()): ?>
            <?php echo $this->getStoreSwitcherHtml() ?>
        <?php endif; ?>

        <?php echo $this->getFormHtml() ?>

        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Products'); ?></h4>
            </div>

            <div class="fieldset fieldset-wide">
                <?php echo $this->getProductGridHtml() ?>
            </div>
        </div>

        <script type="text/javascript">
        </script>
    </form>

<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="content-buttons form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
    <script type="text/javascript">
        var editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
    </script>
<?php echo $this->getFormScripts() ?>