<?php $_product = $this->getProduct();
    $_id = $_product->getId();

 $attributeValue = Mage::getModel('catalog/product')->load($_id)->getRedstageCallforpriceProduct();
#echo Mage::getStoreConfig('customtext/general/enabled');

?>
<?php if($attributeValue!=''){?>
	<strong><?php echo nl2br($attributeValue); ?></strong>
<?php }else {
	?>


<?php $_product = $this->getProduct() ?>

<?php if ($_product->isAvailable()): ?>
    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php echo $this->getPriceHtml($_product) ?>

	
	
	
	
<?php }?>