<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Defconf
 */
?>
<?php 
$selectedIds = $this->getAttributeIdsString(); 
if ($selectedIds):
?>
    <script type="text/javascript">
    defaultConfiguration = new amDefConf();
	document.observe("dom:loaded", function() {
  		defaultConfiguration.select(<?php echo $selectedIds; ?>);
	});
    </script>
<?php endif; ?>