<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Mageplace_Backup
 */

/** @var Mageplace_Backup_Block_Adminhtml_Backup_Item_Js $this */
$_backupItem = $this->getBackupItem();
?>
<script>
    MP.Backup.Item = Class.create();
    MP.Backup.Item.prototype = {
        <?php foreach($_backupItem as $key => $value) : ?>
        <?php $value = (is_string($value) ? ($value ? $value : "''") : ($value ? $value : "0")); $_backupItem[$key] = $value; ?>
        '<?php echo $key; ?>': <?php echo $value; ?>,
        <?php endforeach; ?>

        initialize: function (obj) {
            <?php foreach($_backupItem as $key => $value) : ?>
            this['<?php echo $key; ?>'] = <?php echo $value; ?>;
            <?php endforeach; ?>

            if (Object.isUndefined(obj)) {
                return;
            }

            for (var prop in obj) {
                this[prop] = obj[prop];
            }
        },

        <?php foreach($_backupItem as $key => $value) : ?>
        get<?php echo ucfirst($key); ?>: function () {
            return this.<?php echo $key; ?>;
        },

        <?php endforeach; ?>

        isError: function () {
            return Object.isString(this.getError()) && this.getError() != '';
        }
    };
</script>