<?php
/**
 * Media Gallery & Product Videos extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Mediaappearance
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 **/
?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>mediaappearance/jquery-1.7.2.min.js"></script>


<script type="text/javascript">
    $j=jQuery.noConflict();
    $j(document).ready(function() 
        { 
            Shadowbox.init({
	        overlayOpacity: 0.8,
            handleOversize: 'resize',
	        flashVars: 
                {
   		           skin: '<?php echo Mage::getBaseUrl('js').'mediaappearance/skin01.zip'?>'
  	            },
            });
            Shadowbox.setup($j('.sbox'));//set up links with class of sbox
            $j('a.sbox').live('click',function(e)
                {
                    e.preventDefault();
                    Shadowbox.open(this,{ 
                    player: "inline",
                    height: 200, 
                    width: 240,
                    options:{ /*onFinish: myOpen()*/ },
                    });
                });
            function myOpen()
                {
                    var obj = Shadowbox.getCurrent()
                    var innerBody = document.getElementById('sb-body-inner');
                    //append the new div element containing the description
                    $j(innerBody).append('<div id="sb-description" style="position: fixed; left: auto; opacity: 0; color: #FFFFFF; font-size: 14px;">'+obj.description+'</div>');
                    //get the description container
                    var desctCont = document.getElementById('sb-description');
                    $j(desctCont).addClass('description');
                    //set width
                    $j(desctCont).css({ width: Shadowbox.dimensions.innerWidth + 'px' });
                    /*jQuery(desctCont).css({ top: (Shadowbox.dimensions.innerHeight - jQuery(desctCont).outerHeight()) + 'px' });*/
                    //fade it in
                    $j(desctCont).animate({ opacity: 1 }, 'slow');
                };
            Shadowbox.onReady = function()
                {
                    setTimeout(function()
                        {
                            //filter the titles
                            for (var key in Shadowbox.cache)
                            {
                                var title = Shadowbox.cache[key].title;
                                //split the title from the description
                                var parts = title.split('{|}');
                                //save the title and description
                                if ($(parts).size() == 2)
                                {
                                    Shadowbox.cache[key].title = parts[0];
                                    Shadowbox.cache[key].description = parts[1];
                                }
                        }
                        }, 1000);
                 };
        //Stops loading link
    });
</script>
