<?php
/**
 * Media Gallery & Product Videos extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Mediaappearance
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 **/
?>
<script type="text/javascript">
Shadowbox.init({
    overlayOpacity: 0.8,
	flashVars: {
   		skin: '<?php echo Mage::getBaseUrl('js').'mediaappearance/skin01.zip'?>'
  	}
});
</script>
<?php
	$popupWidth  = Mage::getStoreConfig('mediaappearance/popupsettings/width');
	$popupHeight = Mage::getStoreConfig('mediaappearance/popupsettings/height');
	$autoPlay 	 = Mage::getStoreConfig('mediaappearance/popupsettings/autoplay');
	$playAgain 	 = Mage::getStoreConfig('mediaappearance/popupsettings/playagain');
?>
<?php $pid = $this->getProduct()->getId(); ?>
<?php

	$mediaTable = Mage::getSingleton('core/resource')->getTableName('mediaappearance');
	$mediaStoreTable = Mage::getSingleton('core/resource')->getTableName('media_store');

    $sqry = "select m.* from ".$mediaTable." m where FIND_IN_SET('$pid', product_ids) and status = 1";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
    $select = $connection->query($sqry);
    $media2product = $select->fetchAll();
    
?>

<?php if (count($media2product)): ?>
<div>
<div class="product-img-box">
<div class="more-views">
    <h2><?php echo $this->__('Product Videos') ?></h2>
    <ul>
                  <?php foreach ($media2product as $_media): ?>
                  <?php
						if($_media["mediatype"] == "1") {
							
							$videoURL = Mage::getBaseUrl('media').$_media["filename"];
							$videoRel = 'shadowbox; height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.autoPlay.'}}';
							 if($_media["filethumb"] != "") {
								$imgURL = Mage::helper('mediaappearance')->resizeImage($_media["filethumb"]);
							} else {
								$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon.jpg";
							} 
							
						} elseif ($_media["mediatype"] == "2") {
							
							//For Thumb
							$videoURL = $_media["videourl"];
							$videoData = Mage::helper('mediaappearance')->video_info($_media["videourl"]);
							if ($videoData!==false) {
								if(Mage::getStoreConfig('mediaappearance/general/useyoutubethumb')) {
									$imgURL = $videoData['thumb_large'];	
								} else {
									if($_media["filethumb"] != "") {
										$imgURL = Mage::helper('mediaappearance')->resizeImage($_media["filethumb"]);
									} else {
										$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
									}
								}
							} else {
								if($_media["filethumb"] != "") {
									$imgURL = Mage::helper('mediaappearance')->resizeImage($_media["filethumb"]);
								} else {
									$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
								}
							}
							
							//For Video URL
							if ($videoData!==false) {
								
								$video_type  = $videoData['video_type'];
								$video_id    = $videoData['video_id'];
								if($video_type == "vimeo") {
									$videoRel = "shadowbox;height=".$popupHeight.";width=".$popupWidth.";";
									$videoURL = 'http://vimeo.com/moogaloop.swf?clip_id='.$video_id.'&autoplay='.$autoPlay.'';
								} elseif($video_type == "youtube") {
									$videoRel = 'shadowbox;height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{autostart: '.$autoPlay.'}}';
									$videoURL = "http://www.youtube.com/v/".$video_id;
								} 
								
							} else {
								
								$videoURL = $_media["videourl"];
								$videoRel = 'shadowbox;height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.$autoPlay.'}}';
								
							}
						} else {
							$videoRel = "";
							$videoURL = "#";
							$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
						}	
					?>
                    <li>
                        <a href="<?php echo $videoURL; ?>" title="<?php echo $_media['title']; ?>" rel="<?php echo $videoRel; ?>" >
                        <img src="<?php echo $imgURL; ?>" width="56" height="56" alt="<?php echo $_media['title']; ?>" /></a>
                    </li>
                  <?php endforeach; ?> 
      </ul>
</div>
</div>
</div>
<?php endif; ?>