<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Mageplace_Hideprice
 */
?>
<?php /** @var $this Mageplace_Hideprice_Block_Adminhtml_Catalog_Category_Tab */ ?>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Hide Price'); ?></h4>
	</div>

	<div class="fieldset fieldset-wide" id="group_hp_fieldset_group_hp">
		<legend><?php echo $this->__('Hide Price Settings'); ?></legend>
		<table class="form-list">
			<tr>
				<td class="label">
					<label for="HP_mode"><?php echo $this->__('Mode'); ?></label>
				</td>
				<td class="value" style="text-align: left;">
					<?php $modes = $this->getModes(); ?>
					<select name="HP_mode" id="HP_mode">
						<?php $mode = $this->getCurrentMode(); ?>
						<?php foreach ($this->getModes() as $row) : ?>
							<option value="<?php echo $row['value']; ?>"
									<?php if ($row['value'] == $mode): ?>selected="selected"<?php endif; ?>>
								<?php echo $row['label']; ?>
							</option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td class="label">
					<label for="HP_group"><?php echo $this->__('By Group'); ?></label>
				</td>
				<td class="value" style="text-align: left;">
					<?php $enabledGroups = $this->getEnabledGroups(); ?>
					<select name="HP_group[]" id="HP_group" size="10" multiple="multiple">
						<?php foreach ($this->getGroups() as $row) : ?>
							<option value="<?php echo $row['value']; ?>"
									<?php if (in_array($row['value'], $enabledGroups)): ?>selected="selected"<?php endif; ?>>
								<?php echo $row['label']; ?>
							</option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td class="label">
					<label
						for="HP_children"><?php echo $this->__('Apply only to current category (children categories will have parent categories mode)'); ?></label>
				</td>
				<td class="value" style="text-align: left;">
					<input type="checkbox" <?php if ($this->isExcludeChildren()): ?>checked="checked"<?php endif; ?>
						   name="HP_children" id="HP_children"/>
				</td>
			</tr>
			<tr>
				<td class="label">
					<label for="HP_priority"><?php echo $this->__('Precedence'); ?></label>
				</td>
				<td class="value" style="text-align: left;">
					<input type="text" size="2" name="HP_priority" id="HP_priority" value="<?php echo $this->getPriority(); ?>"/>
				</td>
			</tr>
		</table>
	</div>
</div>


