<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Mageplace_Hideprice
 */
?>
<?php
/**
 * @var $this Mageplace_Hideprice_Block_Adminhtml_Store_Switcher
 */
?>
<?php if ($websites = $this->getWebsites()): ?>
    <p class="switcher"><label for="store_switcher"><?php echo $this->__('Choose Store View') ?>:</label>
        <select name="store" id="store">
            <option value=""><?php echo $this->getDefaultStoreName() ?></option>
            <?php foreach ($websites as $website): ?>
                <?php $showWebsite = false; ?>
                <?php foreach ($website->getGroups() as $group): ?>
                    <?php $showGroup = false; ?>
                    <?php foreach ($this->getStores($group) as $store): ?>
                        <?php if ($showWebsite == false): ?>
                            <?php $showWebsite = true; ?>
                            <optgroup label="<?php echo $website->getName() ?>"></optgroup>
                        <?php endif; ?>
                        <?php if ($showGroup == false): ?>
                            <?php $showGroup = true; ?>
                            <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $group->getName() ?>">
                        <?php endif; ?>
                        <option value="<?php echo $store->getId() ?>">
                            &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $store->getName() ?></option>
                    <?php endforeach; ?>
                    <?php if ($showGroup): ?>
                        </optgroup>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </select>
    </p>
<?php endif; ?>
